# Generated by Django 4.1 on 2022-12-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0002_alter_yoga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
