# Generated by Django 4.1 on 2022-12-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0003_alter_yoga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='image',
            field=models.ImageField(default=2, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
